Added functions from Napalm
FabrizioBrancati/BFKit-Swift pull request #24
Opened 2016-12-14 17:51 UTC by calebkleveter

2016-12-15 08:00 UTC, FabrizioBrancati requested changes
I think this changes will resolve the CI :+1:

2016-12-15 08:00 UTC, FabrizioBrancati commented on Sources/BFKit/Linux/Foundation/ArrayExtension.swift
> +        #if os(Linux)
Here we could use [randomInt](https://github.com/FabrizioBrancati/BFKit-Swift/blob/master/Sources/BFKit/Linux/Foundation/NumberExtension.swift#L56) from number extension

2016-12-15 08:00 UTC, FabrizioBrancati commented on Sources/BFKit/Linux/Foundation/ArrayExtension.swift
> +        if let obj = item {
It's better to call it `object` instead of `obj`

2016-12-15 08:00 UTC, FabrizioBrancati commented on Sources/BFKit/iOS/UIKit/UIViewControllerExtension.swift
> +    public func userErrorAlert(title: String, message: String?, buttonTitle: String = "OK") {
I don't really like this functon, we can make it more generic like `present(title: String, message: String, actions: [UIAlertAction], alertType: UIAlertControllerStyle = .alert)`

2016-12-15 08:00 UTC, FabrizioBrancati commented on Tests/BFKitTests/Linux/Foundation/ArrayExtensionTests.swift
> +   func testRandom() {
This test is failing on Linux, maybe using randomInt we will resolve it

2016-12-15 08:00 UTC, FabrizioBrancati commented on Tests/BFKitTests/Linux/Foundation/ArrayExtensionTests.swift
> +        var arr = array
Rename it with something like `arrayCopy` or something else. I'm sorry I don't like short variable names

2016-12-16 14:05 UTC, calebkleveter commented
I discovered the reason the build was failing. I was calling `XCTFail()` in `.testRandom()`. :face-palm:

2016-12-16 14:13 UTC, FabrizioBrancati requested changes
Yes that was the problem, but now you are always passing the test.
The XCTFail() was not wrong :smile:

2016-12-16 14:13 UTC, FabrizioBrancati commented on Tests/BFKitTests/Linux/Foundation/ArrayExtensionTests.swift
>                  XCTAssert("\(i)" != "\(element)")
What are you testing here?
This is what your test is doing: `if i == element { return i == element } else { return i != element }`.
You are always return true.
If you want to find the random element inside the array you can remove the `else`, add again the `XCTFail()` and add a `return` after the `XCTAssert`

2016-12-16 15:46 UTC, FabrizioBrancati approved these changes

2016-12-16 16:28 UTC, merged